# Generated by Django 4.2.7 on 2023-11-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='note',
            new_name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='destination_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
