# Generated by Django 4.2.7 on 2023-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='uuid',
            field=models.CharField(default='72944ca272e2435584ba416d2ba80a52', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='space',
            name='users',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
