# Generated by Django 4.2.7 on 2023-12-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_space_uuid_alter_post_latitude_alter_post_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='uuid',
        ),
    ]
