# Generated by Django 4.2.7 on 2023-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_space_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='未知', max_length=6),
            preserve_default=False,
        ),
    ]
