# Generated by Django 4.2.7 on 2023-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_post_owner_post_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='duration',
        ),
        migrations.AddField(
            model_name='post',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
