# Generated by Django 4.2.7 on 2024-01-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_post_duration_post_end_post_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
